In [12]:
import numpy as np
import array
a = np.arange(20,30,5)
a

array([20, 25])

In [16]:
a = np.zeros(5)
b = np.ones(6)
a, b


(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1.]))

In [10]:
np.inf + np.inf

inf

In [3]:
np.inf - np.inf

nan

In [8]:
a = 3
b = 7
c = a ** b
c, a, b

(2187, 3, 7)

In [10]:
a = np.ones((3,1))
b = 2*np.transpose(a)
print(a.shape, b.shape)

(3, 1) (1, 3)


In [16]:
a = np.array([0, 1, 8, 27, 111, 222, 344, 555, 877])

In [14]:
a = np.array([27, 343])
a


array([ 27, 343])

In [17]:
np.int64(64)

np.int64(64)

In [22]:
arr = np.array([1,2,3,4,5])
arr*2

array([ 2,  4,  6,  8, 10])

In [25]:
# Списки
emp = [] #пустой
list_range = list(range(10)) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
list_pow = [x**2 for x in range(5)] # Начиная с нуля и до 4 включительно по порядку с шагом 1 и возведением в степень 2
emp, list_range, list_pow


([], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 4, 9, 16])

In [19]:
a = [1, 2, 3, 4, 5]
a[-3], a[-2], a[-1], a[0]

(3, 4, 5, 1)

In [28]:
# NumPy массивы
nuli = np.zeros(5) # [0\. 0. 0. 0. 0.]
edin = np.ones((2, 3)) # 2x3 массив из единиц
ravnomer = np.linspace(0, 100, 21) # равномерно распределит числа от 0 до 100
nuli, edin, ravnomer

(array([0., 0., 0., 0., 0.]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
         55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.]))

In [37]:
a = [1,2,3,4] #обычный массив списком
b = np.array([2,3,4,5,6]) #NumPy массив
b * 2, a * 2, b ** 3 #NumPy позволяет проводить операции с самими элементами, список продублирует

(array([ 4,  6,  8, 10, 12]),
 [1, 2, 3, 4, 1, 2, 3, 4],
 array([  8,  27,  64, 125, 216]))

In [66]:
a = np.array(range(1,13,1))
a[11] = 13 #Замена одиннадцатого значения в массиве на "13"
a[5] = True #Работает потому что продумаНО(Но значение всегда будет паринимать "1")
a ** 2, a * 3, a + a, a - a, a / a

(array([  1,   4,   9,  16,  25,   1,  49,  64,  81, 100, 121, 169]),
 array([ 3,  6,  9, 12, 15,  3, 21, 24, 27, 30, 33, 39]),
 array([ 2,  4,  6,  8, 10,  2, 14, 16, 18, 20, 22, 26]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [77]:
pivasik = ['Dark', 'Pale', 'Ale', 'Lager', 'IPA', 'Kriek']
pivasik.append('Lambic') #Добавляет в конец списка слово из скобок
pivasik.insert(0, 'Rouge De Bruxelles') #Поместиться в позицию с индексом 0, потому что Первое, потому что лучшее
pivasik.extend(['Dubbel', 'Tripel', 'Quadrupel']) #добавит все слова в конец
pivasik.append(3) #Тк это обычный массив списком можно сувать что угодно
pivasik.insert(6, 98989)
pivasik.extend([True, "False"])
shmon = pivasik.pop()#Убирет последний внесенный элемент("False" в нашем случае)
pivasik

['Rouge De Bruxelles',
 'Dark',
 'Pale',
 'Ale',
 'Lager',
 'IPA',
 98989,
 'Kriek',
 'Lambic',
 'Dubbel',
 'Tripel',
 'Quadrupel',
 3,
 True]

In [2]:
# Создание 2D массива
import numpy as np
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Доступ к элементам
mat[1, 2] # 6 (элемент во второй строке, третьем столбце)

# Срезы в многомерных массивах
mat[:, 1], "\n" # [2, 5, 8] (второй столбец)
mat[1:, :2] # [[4, 5], [7, 8]] (подматрица)


array([[4, 5],
       [7, 8]])

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Булева индексация
mask = arr > 5 #Использует все значения численно выше 5
print(arr[mask]) # Массив с условием mask

# Индексация массивами
row_indices = np.array([1, 1]) 
col_indices = np.array([0, 2])
print(arr[row_indices, col_indices]) # Первый элемент берется во 2 строке(1) и первом столбце(0). Второй элемент берется во второй строке(1) и третьей столбце(2)

# Фантомное индексирование (fancy indexing)
print(arr[[0, 2], :][:, [0, 2]]) # Сначала первый срез (1 и 3 строка, все столбцы), затем из этого среза делается срез(1, 3 столбец)


[6 7 8 9]
[4 6]
[[1 3]
 [7 9]]


In [33]:
arr = np.arange(1,13,1)
shape = arr.reshape(6, 2)
t = shape.T
arr1 = np.arange(1,11,2)
arr2 = np.arange(0, 10, 2)
st_ver = np.vstack((arr1, arr2)) # вертикальное объединение
st_hor = np.hstack((arr1, arr2)) # горизонтальное объединение
shape, t, st_ver, st_hor

(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]),
 array([[ 1,  3,  5,  7,  9, 11],
        [ 2,  4,  6,  8, 10, 12]]),
 array([[1, 3, 5, 7, 9],
        [0, 2, 4, 6, 8]]),
 array([1, 3, 5, 7, 9, 0, 2, 4, 6, 8]))

In [38]:
arr1 = range(1,11,2)
arr2 = range(0, 10, 2)
st_ver = np.vstack((arr1, arr2)) # вертикальное объединение
st_hor = np.hstack((arr1, arr2))# горизонтальное объединение
d_type = arr.dtype
shape, t, st_ver, st_hor, d_type

(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]),
 array([[ 1,  3,  5,  7,  9, 11],
        [ 2,  4,  6,  8, 10, 12]]),
 array([[1, 3, 5, 7, 9],
        [0, 2, 4, 6, 8]]),
 array([1, 3, 5, 7, 9, 0, 2, 4, 6, 8]),
 dtype('int64'))

In [45]:
a = np.split(np.arange(9), 3)#делим созданный массив из 9 элеметнтов на 3 равных части
b = np.array([[1, 2, 3], [6, 5, 4], [8, 9, 7]])
c = np.mean(a) #выводит среднее
d = np.mean(a+b)
a + b, a - b, a * b, a / b, c, d

(array([[ 1,  3,  5],
        [ 9,  9,  9],
        [14, 16, 15]]),
 array([[-1, -1, -1],
        [-3, -1,  1],
        [-2, -2,  1]]),
 array([[ 0,  2,  6],
        [18, 20, 20],
        [48, 63, 56]]),
 array([[0.        , 0.5       , 0.66666667],
        [0.5       , 0.8       , 1.25      ],
        [0.75      , 0.77777778, 1.14285714]]),
 np.float64(4.0),
 np.float64(9.0))

In [ ]:
pivasik = ['Dark', 'Pale', 'Ale', 'Lager', 'IPA', 'Kriek']
pivasik.append('Lambic') #Добавляет в конец списка слово из скобок
pivasik.insert(0, 'Rouge De Bruxelles') #Поместиться в позицию с индексом 0, потому что Первое, потому что лучшее
pivasik.extend(['Dubbel', 'Tripel', 'Quadrupel']) #добавит все слова в конец
pivasik.append(3) #Тк это обычный массив списком можно сувать что угодно
pivasik.insert(6, 98989)
pivasik.extend([True, "False"])
shmon = pivasik.pop()#Убирет последний внесенный элемент("False" в нашем случае)
pivasik